[tools]
rojo = { source = "Roblox/rojo-rbx-rojo", version = "=7.2.1" }
selene = { source = "Roblox/Kampfkarren-selene", version = "=0.21.1" }
stylua = { source = "Roblox/JohnnyMorganz-StyLua", version = "=0.15.1" }
luau-lsp = { source = "JohnnyMorganz/luau-lsp", version = "=1.8.1" }
