#!/bin/sh

git clone --depth=1 https://github.com/LPGhatguy/lemur.git modules/lemur
git clone --depth=1 https://github.com/Roblox/TestEZ.git modules/testez
git clone --depth=1 https://github.com/Roblox/Roact.git modules/roact
git clone --depth=1 https://github.com/Roblox/Rodux.git modules/rodux