name: Publish Rotriever Package 
on:
  workflow_dispatch:
jobs:
  composite-publish:
    runs-on: [self-hosted, generic-linux]
    container:
      image: docker.artifactory.rbx.com/rbx-lua-build-tools:latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate access token
        uses: Roblox-ActionsCache/tibdex-github-app-token@v1.4.0
        id: setup_token
        with:
          app_id: ${{ secrets.TOKENS_APP_LUA_ECOSYSTEM_DEPENDENCIES_ID }}
          private_key: ${{ secrets.TOKENS_APP_LUA_ECOSYSTEM_DEPENDENCIES_KEY }}
      - name: Get foreman and run foreman install
        uses: Roblox/setup-foreman@v3
        with:
          token: ${{ steps.setup_token.outputs.token }}
          allow-external-github-orgs: true
      - name: Composite Publish
        uses: Roblox/rotriever-registry-workflows/composite-publish@v1
        with:
          artifactory-token: ${{ secrets.ROBLOX_ARTIFACTORY_CI_PUBLISH_BEARER_TOKEN }}
          github-token: ${{ steps.setup_token.outputs.token }}